fxge: fix missing windows include in cfx_renderdevice.h
This resulted in a build failure here:
In file included from .../pdfium/core/fxge/cfx_drawutils.cpp:13:
.../core/fxge/cfx_renderdevice.h(74,7): error: unknown type name 'HDC'
   74 |       HDC hdc,
      |       ^

It seems this started after commit
fc790866bf26d977b2ea3a0c3938bb52895309ea (Consolidate CFX_RenderDevice
and remove CPDF_WindowsRenderDevice, 2026-06-29): the Windows-DC code
was moved from cpdf_windowsrenderdevice.h to cfx_renderdevice.h but the
windows.h include wasn't moved.

Given that it looks like every other pdfium header that uses HDC
includes <windows.h> directly (core/fxge/win32/cpsoutput.h etc.), just
add the missing include here as well, conditionally.

Change-Id: Ie9920b2031148f7781862502905d999ce045b014
Reviewed-on: https://pdfium-review.googlesource.com/c/pdfium/+/154690
Reviewed-by: Tom Sepez <tsepez@chromium.org>
Reviewed-by: Lei Zhang <thestig@chromium.org>
Commit-Queue: Lei Zhang <thestig@chromium.org>